# -*- coding: utf-8 -*-
"""TASK-6-SPARKS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kyT6lj492g6w6JovjEYqbGNak3Qzy7IY
"""

!pip install --upgrade pandas-datareader

# Importing libraries in Python
import sklearn.datasets as datasets
import pandas as pd
import numpy as np

# Loading the iris dataset
iris=datasets.load_iris()

# Forming the iris dataframe
df=pd.DataFrame(iris.data, columns=iris.feature_names)
print(df.head())

y=iris.target
print(y)

#Implementing the Decision tree Algorithm
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(df,y)

# Install required libraries
!pip install pydotplus
!apt-get install graphviz -y

# Import necessary libraries for graph viz
from six import StringIO 
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

# Visualize the graph
dot_data = StringIO()
export_graphviz(dt, out_file=dot_data, feature_names=iris.feature_names,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())